defaults: &defaults
  host: '127.0.0.1'
  autocreate_indexes: false
  allow_dynamic_fields: true
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: quora_development

test:
  <<: *defaults
  database: quora_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: '127.0.0.1'
  database: quora

