default: &defaults
  # 网站名称
  app_name: "Quora"
  # 页脚版权
  foot_html: "&copy; Quora <a href='http://github.com/huacnlee/quora/' rel='nofollow'>code</a>."
  # 网站的域名
  domain: "127.0.0.1:3000"
  # 配置图片的域名
  upload_url: "http://127.0.0.1:3000/uploads"
  # 设置管理员，在下面填写需要设置为管理员的用户 email
  admin_emails: 
    - "huacnlee@gmail.com"
  smtp_username: 'support@huacnlee.com'
  smtp_password: 'SU_123123'
  google_analytics_id: "UA-19702050-1"
  # 是否开放注册
  allow_register: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  app_name: "者也"
  # 页脚版权
  foot_html: "&copy; 者也 zheye.org - 非营利问答平台, 开源项目，<a href=\"http://github.com/huacnlee/quora\">代码</a>。内测期间，如有问题还请谅解。<br />目前暂时只支持Chrome浏览器，请在 1280 宽度以上的分辨率下面浏览。<br />诚邀有志有能之士参与这个项目，需要1个前端，1个推广。"
  # 网站的域名
  domain: "zheye.org"
  # 配置图片的域名
  upload_url: "http://zheye.org/uploads"
